name: Security Scanning and Compliance

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Weekly scan

permissions:
  contents: read
  security-events: write
  pull-requests: read

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run npm audit
      run: npm audit --audit-level=moderate
      
    - name: Run Semgrep security scan
      uses: semgrep/semgrep-action@v1
      with:
        config: auto
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        
    - name: CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        languages: javascript, typescript
        
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: high
        
  signed-commit-check:
    name: Verify Signed Commits
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Verify commit signatures
      run: |
        # Check if commits are signed
        git log --show-signature --oneline -10 || echo "Warning: Some commits may not be signed"
        
    - name: Check branch protection compliance
      run: |
        echo "Verifying branch protection rules are enforced"
        # Additional compliance checks can be added here